suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(stringr)
  library(tidyr)
})

scan_paths <- c(
  "README.md",
  "analysis/session1_foundations_followalong.Rmd",
  "analysis/session2_measurement_mapping_followalong.Rmd",
  "analysis/session3_models_extensions_followalong.Rmd",
  "analysis/master_tariff_teaching_workbook.Rmd",
  "analysis/student_workbook_client_facing.Rmd",
  "analysis/guided_student_workbook.Rmd"
)

missing_paths <- scan_paths[!file.exists(scan_paths)]
if (length(missing_paths) > 0) {
  stop("Missing text scan files: ", paste(missing_paths, collapse = ", "))
}

scan_patterns <- c(
  "chatgpt",
  "openai",
  "codex",
  "gemini",
  "large language model",
  "\\bllm\\b",
  "as an ai",
  "generated by ai",
  "ai-generated",
  "ian to jubili"
)

joined_pattern <- str_c(scan_patterns, collapse = "|")

issues <- lapply(scan_paths, function(path) {
  lines <- read_lines(path, skip_empty_rows = FALSE, progress = FALSE)
  tibble(
    file = path,
    line = seq_along(lines),
    text = lines
  ) %>%
    filter(str_detect(str_to_lower(text), joined_pattern))
}) %>%
  bind_rows() %>%
  mutate(text = str_squish(text))

if (nrow(issues) > 0) {
  print(issues, n = min(50, nrow(issues)))
  stop(
    "Client-facing text scan failed. Remove flagged wording and rerun code/check_client_text.R."
  )
}

message("Client-facing text scan passed (no AI-signaling phrases found).")
